apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
      - name: java-microservice
        image: igris08/java-microservice:latest
        ports:
        - containerPort: 8080
