apiVersion: v1
kind: Service
metadata:
  name: java-microservice-service
spec:
  selector:
    app: java-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  
